### ISSUE TITLE
Relationships in schema does not show saved source/target

### ISSUE THREAD

**Issue by octref** [underlay/underlay.org#61] opened 2022-03-23 13:39 UTC
<img width="666" alt="image" src="https://user-images.githubusercontent.com/4033249/159712558-b9c34847-7af8-430c-a61e-77519e9b6f40.png">

Repro:

- Make selections for `source` and `target`
- Save schema
- Reload

**Comment by isTravis** [comment] 2022-03-23 13:42
I can't reproduce this on my [test collection](https://dev.underlay.org/travis/double/schema). Which collection are you getting this bug with?

**Comment by octref** [comment] 2022-03-24 11:08
This one: https://dev.underlay.org/pine/test-collection/schema

**Comment by isTravis** [comment] 2022-06-14 19:41
Fixed in a recent PR

**Closed by isTravis** 2022-06-14 19:41 UTC
Labels: bug
